# 
# GitHub Actions workflow.
#
# Delete deployment.
#

name: Delete deployment

on:
  #
  # Allows deletion to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      #
      # Installs Kubectl and connects it to the cluster.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      # Make scripts executable
      - name: Make delete.sh executable
        run: chmod +x ./scripts/delete.sh

      # 
      # Delete deployment.
      #
      - name: Delete Deployments
        run: ./scripts/delete.sh
